# Generated by Django 5.1.1 on 2024-09-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link_collections'),
        ('api', '0003_populate_test_data'),
    ]

    operations = [
    ]
